version: "3.3"
services:
  postgres:
    container_name: pg-note-app
    image: postgres:latest
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_DB=${PG_DB} #optional (specify default database instead of $POSTGRES_DB)
      - POSTGRES_PORT=${DB_PORT}
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  note-backend:
    container_name: note-backend
    build: ./backend
    ports:
      - "${BACKEND_PORT}:3000"
    environment:
      - DB_HOST=postgres
      - DB_USER=${PG_USER}
      - DB_PASSWORD=${PG_PASS}
      - DB_DATABASE=${PG_DB}
      - DB_PORT=${DB_PORT}
    depends_on:
      - postgres

  note-app:
    container_name: note-app
    build: ./frontend
    ports:
      - "${FRONTEND_PORT}:3001"
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
      - BACKEND_HOST=note-backend
    depends_on:
      - note-backend
