version: "3.3"
services:
  postgres:
    container_name: pg-note-app
    image: postgres:latest
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_DB=${PG_DB} #optional (specify default database instead of $POSTGRES_DB)
    ports:
      - "${DB_PORT}:${DB_PORT}"
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
